sudo: required
  
language: python

python:
    - 2.7

addons:
    apt:
        packages:
            - build-essential
            - curl
            - git
            - pkg-config
            - software-properties-common
            - python-dev
            - python3-dev
            - libfftw3-dev
            - libgdbm-dev
            - libatlas-base-dev

script:
    - sudo pip install \
        setuptools \
        numpy==1.13.3 \
        matplotlib==2.1.1 \
        scipy==0.19.1
    - sudo pip install \ 
        lsl==1.2.5
    - cd tests
    - ./simple_test.sh

cache:
  directories:
    - $HOME/eLWA/tests

