sudo: required
  
language: python

python:
    - 2.7
    - 3.6
    ## PyPy versions
    #- pypy2.7-6.0
    #- pypy3

addons:
    apt:
        packages:
            - build-essential
            - curl
            - git
            - pkg-config
            - software-properties-common
            - python-dev
            - python3-dev
            - libfftw3-dev
            - libgdbm-dev
            - libhdf5-dev

before_install:
    - sudo add-apt-repository -y ppa:deadsnakes/ppa
    - sudo apt-get -q update
    - sudo apt-get -y install python3.6 python3.6-dev

install:
    - pip install \
        setuptools \
        numpy \
        matplotlib \
        scipy \
        h5py \
        jinja2
    - pip install git+https://github.com/lwa-project/lsl.git
    - pip install pylint
    - curl https://fornax.phys.unm.edu/lwa/data/finals2000A.data -o $HOME/.lsl/geodesy_cache/finals2000A.data --create-dirs

script:
    - cd tests
    - python -m unittest discover

cache:
    directories:
      - $HOME/.lsl
